### ISSUE TITLE
Code release!

### ISSUE THREAD

**Issue by forresti** [Aubrey-ao/HumanBehaviorAnimation#1]
I just wanted to say I really enjoyed reading your paper and watching your demo. I am looking forward to the code release!

**Comment by rohith-k20** [comment]
Is the code releasing any time soon??

**Comment by Aubrey-ao** [comment]
Thanks for your attention.

We will start to release our codes (approved parts) and dataset in several months. Due to the complexity of our system (and business-related approval process), it will take some time to prepare.

Besides, to fill the gap between the academic demo and a real production-ready system, we will update some improvements we have made in an incremental manner.

**Comment by hmthanh** [comment]
I'm looking forward for Code release.

**Comment by nagyrajmund** [comment]
Is there any chance you could release an inference-only pipeline alongside a checkpoint for running comparisons to your model?

**Comment by Aubrey-ao** [comment]
A [simplified version](https://github.com/Aubrey-ao/HumanBehaviorAnimation/tree/main/HumanBehaviorAnimation/RhythmicGesticulator/Simplified_Version) has been approved for release. If have any problem to improve the performance, plz contact me : )
